"use client";
import * as React from "react";
import { useRouter } from "next/navigation";
import type { Route } from "next";
import { MoreVertical, Pencil, Trash2 } from "lucide-react";
import {
  DropdownMenu,
  DropdownMenuTrigger,
  DropdownMenuContent,
  DropdownMenuItem,
} from "@/components/ui/dropdown-menu";
import { EditInstanceDialog } from "@/features/recurring/components/edit-instance-dialog";
import { detachInstance } from "@/features/recurring/actions";
import { deleteTransaction } from "../actions";
import type { TxListItem } from "../queries";
import { TransactionEditSheet } from "./transaction-edit-sheet";

// Per-row menu: Edit (income/expense only) + Delete. A row generated by a
// recurring rule routes Edit through a 2-mode dialog (this-instance-only vs.
// edit-series) before reaching the normal edit sheet.
export function TransactionRowActions({
  tx,
  accounts,
}: {
  tx: TxListItem;
  accounts: { id: string; name: string }[];
}) {
  const router = useRouter();
  const [pending, startTransition] = React.useTransition();
  const [editOpen, setEditOpen] = React.useState(false);
  const [instanceOpen, setInstanceOpen] = React.useState(false);
  const isTransfer = tx.kind === "transfer";
  const isRecurring = tx.recurringRuleId !== null;

  function handleEdit() {
    if (isRecurring) setInstanceOpen(true);
    else setEditOpen(true);
  }

  // "This only": detach from the rule, then edit as a normal row.
  async function handleEditThisOnly() {
    setInstanceOpen(false);
    await detachInstance({ transactionId: tx.id });
    setEditOpen(true);
  }

  // "Edit series": jump to the rule's edit sheet on the recurring page.
  function handleEditSeries() {
    setInstanceOpen(false);
    router.push(`/recurring?edit=${tx.recurringRuleId}` as Route);
  }

  return (
    <>
      <DropdownMenu>
        <DropdownMenuTrigger
          aria-label="Tùy chọn giao dịch"
          className="flex h-9 w-9 items-center justify-center rounded-md text-fg-subtle hover:bg-surface-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
        >
          <MoreVertical size={18} aria-hidden="true" />
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end">
          {!isTransfer && (
            <DropdownMenuItem onSelect={handleEdit}>
              <Pencil size={16} aria-hidden="true" /> Sửa
            </DropdownMenuItem>
          )}
          <DropdownMenuItem
            disabled={pending}
            className="text-expense"
            onSelect={(e) => {
              e.preventDefault();
              const ok = window.confirm(
                isTransfer ? "Xóa cả cặp giao dịch chuyển khoản?" : "Xóa giao dịch này?",
              );
              if (ok) startTransition(() => void deleteTransaction({ id: tx.id }));
            }}
          >
            <Trash2 size={16} aria-hidden="true" /> Xóa
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>

      {isRecurring && !isTransfer && (
        <EditInstanceDialog
          open={instanceOpen}
          onOpenChange={setInstanceOpen}
          onEditThisOnly={handleEditThisOnly}
          onEditSeries={handleEditSeries}
        />
      )}

      {!isTransfer && (
        <TransactionEditSheet
          tx={{
            id: tx.id,
            kind: tx.kind as "income" | "expense",
            amount: Math.abs(tx.amount),
            accountId: tx.accountId,
            categoryId: tx.categoryId,
            note: tx.note,
            occurredAt: tx.occurredAt,
          }}
          accounts={accounts}
          open={editOpen}
          onOpenChange={setEditOpen}
        />
      )}
    </>
  );
}
