"use client";
import { FilePen, ListChecks } from "lucide-react";
import { Sheet, SheetContent } from "@/components/ui/sheet";

// Shown when the user edits a transaction that was generated by a recurring rule.
// Two modes only: edit just this row (detaches it from the rule), or edit the
// whole series going forward. Past materialised rows are never rewritten.
export function EditInstanceDialog({
  open,
  onOpenChange,
  onEditThisOnly,
  onEditSeries,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onEditThisOnly: () => void;
  onEditSeries: () => void;
}) {
  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent title="Giao dịch định kỳ">
        <p className="mb-4 text-sm text-fg-muted">
          Giao dịch này được tạo từ một quy tắc định kỳ. Bạn muốn sửa phần nào?
        </p>
        <div className="flex flex-col gap-3">
          <Choice
            icon={<FilePen size={20} aria-hidden="true" />}
            title="Chỉ giao dịch này"
            desc="Tách khỏi quy tắc và chỉ sửa mục này. Quy tắc giữ nguyên."
            onClick={onEditThisOnly}
          />
          <Choice
            icon={<ListChecks size={20} aria-hidden="true" />}
            title="Cả chuỗi"
            desc="Sửa quy tắc cho các lần tới. Các giao dịch đã tạo trước đó không đổi."
            onClick={onEditSeries}
          />
        </div>
      </SheetContent>
    </Sheet>
  );
}

function Choice({
  icon,
  title,
  desc,
  onClick,
}: {
  icon: React.ReactNode;
  title: string;
  desc: string;
  onClick: () => void;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className="flex items-start gap-3 rounded-2xl border border-border p-4 text-left transition-colors hover:bg-surface-muted"
    >
      <span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-surface-muted text-fg-muted">
        {icon}
      </span>
      <span className="min-w-0">
        <span className="block font-semibold text-fg">{title}</span>
        <span className="mt-0.5 block text-[12px] text-fg-muted">{desc}</span>
      </span>
    </button>
  );
}
